name: wenz_draw
description: A high-performance Flutter infinite canvas drawing SDK.
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.29.0

flutter:
