name: wenz_draw_example
description: Example app for the wenz_draw infinite canvas SDK.
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  wenz_draw:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
